### ISSUE TITLE
SOXS mdark - progress tracking

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/soxspipe#27]

**Comment by marcolandoni** [comment]
Ask if the Master Dark in the NIR is reuired for the scince object only.
We have OFF frames for the calibration images (FLAT, ARC,...)

**Comment by thespacedoctor** [comment]
mdark recipe officially released in v0.3.1. Here's the changelog for this version:

* **FEATURE:** recipe & command-line tool for master dark creation (`mdark`)
* **ENHANCEMENT:** default binning add to detector settings file
* **ENHANCEMENT:** added mixed exposure time unit test for dark-frames
* **ENHANCEMENT:** added default values for gain and ron in the detector settings files. Default values can be overwritten if correct GAIN and RON are found in fits-headers (overwritten for UVB and VIS but not NIR for XShooter)
* **ENHANCEMENT:** can now interrupt "~" as home directory in sof file path
* **FIXED:** binning factor used when trimming frames
* **FIXED:** the trimming dimensions of NIR frames - bad-pixel map now aligns correctly with data frame
* **FIXED:** science pixels for all 3 xshooter detectors in parameters file

[![](https://live.staticflickr.com/65535/50266169258_b91daa669e_z.png)](https://live.staticflickr.com/65535/50266169258_b91daa669e_o.png)
