### ISSUE TITLE
Missing configuration file, and contradicting XShooter filename conventions after a fresh install

### ISSUE THREAD

**Issue by naamach** [thespacedoctor/soxspipe#296]
Hello,

I followed the "Quick Start" guide, and ran into some issues running the XShooter data demo (as well as any other command from the command line).
There seem to be two issues:

1. A missing `$HOME/.config/soxspipe/soxspipe.yaml` file.
2. Sometimes the `soxspipe/resources/xsh_keywords.yaml` file is referred to as `XSH_keywords.yaml`.

The first issue occurred when I tried running `soxspipe prep .` or `soxspipe session ls`.
To solve this issue, I manually created a `$HOME/.config/soxspipe/` directory, copied the `soxs_default_settings.yaml` file to that folder, and renamed it `soxspipe.yaml`. I then had to edit line #314 in that file from `filename: /Users/Dave/.config/soxspipe/soxspipe.log` to a local folder.

Afterwards I was able to run `soxspipe session ls`, but when I tried to run `soxspipe prep .` I encountered the second issue, where the pipeline was looking for `XSH_keywords.yaml` instead of `xsh_keywords.yaml`. I manually renamed the file to `XSH_keywords.yaml`, and then I was able to run `soxspipe prep .`.
But then when I tried to run `soxspipe reduce all .`, it was looking for `xsh_keywords.yaml`, so I had to rename the file back to `xsh_keywords.yaml` in order for the script to run.

Thanks!

**Comment by thespacedoctor** [comment]
Hi Na'ama,

Are you working with Sagi? Thanks for this detailed bug report. Can you let us know which platform/OS you are working on?

cheers,  
Dave

**Comment by naamach** [comment]
Hi Dave,

Yes, I'm working with Sagi. :) Starting to write a pipeline for MAST.
I'm working on Ubuntu 20.04.6.

Thanks,
Na'ama

**Comment by thespacedoctor** [comment]
Hi Na'ama,

I believe the case sensitivity issues have been fixed in v0.11.1. When you attempt a full reduction on Ubuntu, there may be other issues waiting to appear. If you report them here, I will try to fix them.

**Comment by naamach** [comment]
Hi Dave,

Great, thanks!
If I encounter any issues, I'll report them here.
