### ISSUE TITLE
soxs order centre - write the logic to juptyer notebook

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/soxspipe#34]
Starting from the X and Y polynomials for each order resulting from `soxs-predict`, write code to capture the central order positions from the single-pinhole lamp flat frames.

This may be from generating an array of pixels in say the Y directory (e.g. 1-2048) and for each column measure the X-pixel where a 1D gaussian best fits the profile of the continuum.

**Comment by marcolandoni** [comment]
Logic under development.
Following strictly xsh_follow_continuum

**Comment by marcolandoni** [comment]
Logic completed. 
Defining QCs and residuals, moving the new soxs_predict interface to soxs_ordercentre

**Comment by marcolandoni** [comment]
Logic completed. Jupyter notebook updated.
Need to define QCs, but in a later stage.
