### ISSUE TITLE
Move to a SQLite database to store persistent data

### ISSUE THREAD

**Issue by marcolandoni** [thespacedoctor/soxspipe#37]
Think about the architecture for putting an SQLite database to store:

- Detailed logs
- Flow of the frames between recipes and products
- Intermediate parameters computed by each recipe

**Comment by thespacedoctor** [comment]
Panda can read and write to SQLite directly making our job much easier here. Example usage:

<https://towardsdatascience.com/python-pandas-and-sqlite-a0e2c052456f>

I plan to refactor code so far to write CSV files/table to SQLite database.

**Comment by thespacedoctor** [comment]
We now have a SQLite database for the data-organiser. If needed, we can start to use this database to store extra information.
